# Generated by Django 3.2.5 on 2021-08-27 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collar_app', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='job',
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='collar_app.category'),
        ),
    ]
