# Generated by Django 3.2.5 on 2021-08-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collar_app', '0003_auto_20210827_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='none', max_length=45),
        ),
    ]
