# Generated by Django 3.2.5 on 2021-08-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collar_app', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='none', null=True),
        ),
    ]
