# Generated by Django 2.2 on 2021-08-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_address',
            name='city',
            field=models.CharField(max_length=95, null=True),
        ),
    ]
