# Generated by Django 3.2.5 on 2021-08-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0002_alter_user_isworker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isWorker',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
